name: seurat2
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.3.3 #4.1.3
  - r-tidyverse=2.0.0 #1.3.2
  - r-rmarkdown=2.26 #2.17
  - r-showtext=0.9_7 #0.
  - r-languageserver=0.3.16
  - r-httpgd=1.3.1
  - radian=0.6.13
  - r-jsonlite=1.8.7
  - jupyter=1.0.0
  - r-irkernel=1.3.2
  - r-here=1.0.1
  - r-seurat
  - genomedk::r-sccustomize
  
